name: Serverless CI/CD

on:
  push:
    branches:
      - serverless

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "DB_URI=${{ secrets.DB_URI }}" > .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "LOCATION_IQ_API_KEY=${{ secrets.LOCATION_IQ_API_KEY }}" >> .env
          echo "AWS_API_ENDPOINT=${{ secrets.AWS_API_ENDPOINT }}" >> .env
        env:
          DB_URI: ${{ secrets.DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          LOCATION_IQ_API_KEY: ${{ secrets.LOCATION_IQ_API_KEY }}
          AWS_API_ENDPOINT: ${{ secrets.AWS_API_ENDPOINT }}

      - name: Deploy to AWS
        run: npx serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1 # Replace with your desired AWS region
